### ISSUE TITLE
Icon Request : Spyder

### ISSUE THREAD

**Issue by Atharvkote** [onemarc/tech-icons#2]
Was Looking for some icons, Got many of those except the Sypder. You know but just for clarification purposes,it  is a Development Enviroment in Anaconda Distribution.Hope you add it as soon as possible.

**Comment by onemarc** [comment]
Added icons: spyder, spyder-dark, spyder-light. I hope this is what you were talking about.

**Comment by Atharvkote** [comment]
Yeah  ,Thanks Mate!

**Comment by Atharvkote** [comment]
Closing issue from my side ,thanks for the help🙂
