### ISSUE TITLE
request for additional icons

### ISSUE THREAD

**Issue by b3nkang** [onemarc/tech-icons#5]
could you add icons for the following?

`Vite, Vitest, Sass, Vercel, Express.js, JUnit, Latex, Gunicorn, Kaggle`

many thanks!

**Comment by onemarc** [comment]
Yeah, I'm working on it, those icons will be soon, but "Saas" already added.

**Comment by b3nkang** [comment]
No, not `Saas`, but `Sass` (or also known as `Scss`), the superset of `CSS`. Here's the logo: 
![image](https://github.com/onemarc/tech-icons/assets/134336066/e2e3718f-d17d-4ae2-af70-4c8f8c146ff5)

**Comment by onemarc** [comment]
**All the icons you requested have been added.**

**Comment by b3nkang** [comment]
great, thanks so much - i think one is missing though, `Vercel`- if you could add that in that'd be much appreciated!

**Comment by onemarc** [comment]
Added.

**Comment by b3nkang** [comment]
thank you so much!!
