### ISSUE TITLE
README examples have incorrect filepath

### ISSUE THREAD

**Issue by b3nkang** [onemarc/tech-icons#6]
currently:
`<a href="#"><img src="https://github.com/onemarc/tech-icons/blob/main/icons/NAME_OF_ICON.svg" width="50"></a>`

correct:
`<a href="#"><img src="https://github.com/onemarc/tech-icons/raw/main/icons/NAME_OF_ICON.svg" width="50"></a>`

`blob->raw` fixed the image issues on my end

**Comment by onemarc** [comment]
I'll look into it.

**Comment by onemarc** [comment]
Sorry it took so long. I checked that everything works, but just in case, I added information about it to the documentation.

**Comment by onemarc** [comment]
Sorry it took so long. I checked that everything works, but just in case, I added information about it to the documentation.
